// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUmXryK1N9cBHUp7XrOHz-yKfI817dWRg',
    appId: '1:117365600577:web:1f882b851a4657185231c0',
    messagingSenderId: '117365600577',
    projectId: 'realmoney-9b2cf',
    authDomain: 'realmoney-9b2cf.firebaseapp.com',
    storageBucket: 'realmoney-9b2cf.firebasestorage.app',
    measurementId: 'G-0X67X2FDES',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0eKDAsESaXykV2-ITK59wHuqcbWwD4K4',
    appId: '1:117365600577:android:78696386043949a65231c0',
    messagingSenderId: '117365600577',
    projectId: 'realmoney-9b2cf',
    storageBucket: 'realmoney-9b2cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYzeM4kIPewoH1SDY0usDO6pKv174sa4U',
    appId: '1:117365600577:ios:cc3954a470b52c9f5231c0',
    messagingSenderId: '117365600577',
    projectId: 'realmoney-9b2cf',
    storageBucket: 'realmoney-9b2cf.firebasestorage.app',
    iosBundleId: 'tz.realmoney.borrower.borrowerMobile',
  );
}
